"""referral and therapist

Revision ID: 604434a9ead3
Revises: 57f4f2c09b21
Create Date: 2023-10-11 22:20:20.538480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604434a9ead3'
down_revision = '57f4f2c09b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('Surname', sa.String(), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('OfficeAddress', sa.String(), nullable=True),
    sa.Column('TherapistType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('GPName', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('GPAddress', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('GPPhone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ReceivedTherapyBefore', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('usedPsychologicalServices', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('MentalHealthDiagnosis', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('MentalHealthAssessment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('Medication', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('TraumaticExperience', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ProfessionalsWorkingWithYou', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('MainDifficulty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('PriorityScore', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Notes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ReferralType', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('preferredTherapyMethod', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('preferredTime', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('eligibleForSupport', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isProcessed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('TherapistId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'therapists', ['TherapistId'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('TherapistId')
        batch_op.drop_column('isProcessed')
        batch_op.drop_column('eligibleForSupport')
        batch_op.drop_column('preferredTime')
        batch_op.drop_column('preferredTherapyMethod')
        batch_op.drop_column('ReferralType')
        batch_op.drop_column('Notes')
        batch_op.drop_column('PriorityScore')
        batch_op.drop_column('MainDifficulty')
        batch_op.drop_column('ProfessionalsWorkingWithYou')
        batch_op.drop_column('TraumaticExperience')
        batch_op.drop_column('Medication')
        batch_op.drop_column('MentalHealthAssessment')
        batch_op.drop_column('MentalHealthDiagnosis')
        batch_op.drop_column('usedPsychologicalServices')
        batch_op.drop_column('ReceivedTherapyBefore')
        batch_op.drop_column('GPPhone')
        batch_op.drop_column('GPAddress')
        batch_op.drop_column('GPName')

    op.drop_table('therapists')
    # ### end Alembic commands ###
