"""inital commit

Revision ID: baa14b9c980c
Revises: 
Create Date: 2023-10-11 23:12:05.174194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa14b9c980c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('Surname', sa.String(), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('OfficeAddress', sa.String(), nullable=True),
    sa.Column('TherapistType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('Surname', sa.String(), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.Column('GPName', sa.String(), nullable=True),
    sa.Column('GPAddress', sa.String(), nullable=True),
    sa.Column('GPPhone', sa.String(), nullable=True),
    sa.Column('ReceivedTherapyBefore', sa.Boolean(), nullable=True),
    sa.Column('usedPsychologicalServices', sa.Boolean(), nullable=True),
    sa.Column('MentalHealthDiagnosis', sa.Boolean(), nullable=True),
    sa.Column('MentalHealthAssessment', sa.Boolean(), nullable=True),
    sa.Column('SelfHarm', sa.Boolean(), nullable=True),
    sa.Column('Medication', sa.Boolean(), nullable=True),
    sa.Column('TraumaticExperience', sa.Boolean(), nullable=True),
    sa.Column('ProfessionalsWorkingWithYou', sa.Boolean(), nullable=True),
    sa.Column('MainDifficulty', sa.String(), nullable=True),
    sa.Column('PriorityScore', sa.Integer(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.Column('ReferralType', sa.String(), nullable=True),
    sa.Column('preferredTherapyMethod', sa.String(), nullable=True),
    sa.Column('preferredTime', sa.String(), nullable=True),
    sa.Column('eligibleForSupport', sa.Boolean(), nullable=True),
    sa.Column('isProcessed', sa.Boolean(), nullable=True),
    sa.Column('TherapistId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TherapistId'], ['therapists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    op.drop_table('therapists')
    # ### end Alembic commands ###
